---
kind: Service
apiVersion: v1
metadata:
  name: minio
  labels:
    app: minio
spec:
  ports:
    - port: 9000
      name: minio
      targetPort: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: dataverse
