---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../../../k8s/dataverse

images:
  - name: iqss/dataverse-k8s
    newName: ghcr.io/nfdi4health/csh-deployment/dataverse
    newTag: latest

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value: [{ name: gh-container-creds }]

patchesStrategicMerge:
  - patch-pvc.yaml
#  - patch-svc.yaml
  - patch-pod-s3-secret.yaml
  - patch-pull-always.yaml
#  - sidecars/ssl/patch.yaml

resources:
  - ingress.yaml
#  - sidecars/ssl/config.yaml
