---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dataverse
spec:
  template:
    spec:
      volumes:
        - name: s3-secret
          secret:
            secretName: dataverse-s3
      containers:
        - name: dataverse
          volumeMounts:
            - name: s3-secret
              mountPath: "/secrets/s3"
              readOnly: true
