---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: dataverse
spec:
  template:
    spec:
      containers:
        - name: dataverse
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "8Gi"
